# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  encoding: utf8
  host: localhost
  database: db/development.sqlite3

integration:
  encoding: utf8
  host: localhost
  adapter: mysql2
  database: <%= ENV['DB_DATABASE'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

production:
  encoding: utf8
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_DATABASE'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
